### ISSUE TITLE
Spacy requirement

### ISSUE THREAD

**Issue by isaacngym** [zzcoolj/corpus2graph#16]
Installed everything as per the readme.

When I use the command corpus2graph in command line I get the following:

```
(corpus2graph) lucky@lucky-ThinkPad-T440:~/t8/cs-personal/corpus2graph$ corpus2graph
Traceback (most recent call last):
  File "/home/lucky/anaconda3/envs/corpus2graph/bin/corpus2graph", line 11, in <module>
    load_entry_point('corpus2graph', 'console_scripts', 'corpus2graph')()
  File "/home/lucky/anaconda3/envs/corpus2graph/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/lucky/anaconda3/envs/corpus2graph/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/lucky/anaconda3/envs/corpus2graph/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/lucky/anaconda3/envs/corpus2graph/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/lucky/Dropbox/Term 8/cs-personal/corpus2graph/corpus2graph/__init__.py", line 1, in <module>
    from .word_processor import FileParser, WordPreprocessor, Tokenizer
  File "/home/lucky/Dropbox/Term 8/cs-personal/corpus2graph/corpus2graph/word_processor.py", line 5, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'

```

Is it a req that was not properly installed?

**Comment by monajalal** [comment]
$ pip install -U spacy

https://spacy.io/usage
